<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="bdc6-dx-9r31t72" ignored="0" name="Test" tests="1" failures="1" timestamp="27 Mar 2020 04:16:24 GMT" time="0.066" errors="0">
  <testcase name="login" time="0.019" classname="demo.NewTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [5]
at demo.NewTest.login(NewTest.java:14)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Test -->
